export default {
    appName: "SaveEntry",
    searchHere: "Search here",
    checkedIn: "Checked in",
    checkedInPlaces: "Checked in places",
    lastVisited: "Last visited",
    pinnedLocations: "Pinned locations",
    yourLocations: "Your locations",
    openURL: "Open SafeEntry",
    rescanQR: "Rescan QR code",
    rename: "Rename",
    deleteLocation: "Delete location",
    markCheckedIn: "Mark as checked in",
    markCheckedOut: "Mark as checked out",
    pinLocation: "Pin location",
    unpinLocation: "Unpin location",
    youNeedToAllowPermission: "You need to grant access to your camera to enable QR code scanning.",
    cannotAccessCamera: "Where's your camera?",
    grantAccess: "Grant access"
};